### PR TITLE
Regenerate release workflows

### PR DESCRIPTION
**Pull request by fiunchinho**
I used the `app` flavour. Not sure about that though.

### CODE REVIEW

**Comment by fiunchinho** [comment]
going with a ping

**Comment by kopiczko** [comment]
Why not adding it to `giantswarm/github` instead?

**Comment by fiunchinho** [comment]
I didn't know which team to make responsible for this repository.

**Comment by kopiczko** [comment]
> I didn't know which team to make responsible for this repository.

Then it should go to the top.

**Comment by fiunchinho** [comment]
Sounds good to me https://github.com/giantswarm/github/pull/41

**Pull request merged**
