### PR TITLE
lister: extract types from Response type

### PR DESCRIPTION
**Pull request by kopiczko**

### CODE REVIEW

**Comment by kopiczko** [comment]
> Fine for now but I would like to have the types in separate packages in the future. This became necessary with separate packages for defaulting and validation and I think it is a good practise in general.

I think this is anti-pattern. I haven't seen anything like that in known open source codebases (of course my knowledge is limited and I'm happy to learn if I'm wrong). Packages should a units of functionality. I'm strongly against that.

Also see: https://dave.cheney.net/practical-go/presentations/qcon-china.html#_consider_fewer_larger_packages

**Comment by xh3b4sd** [comment]
Thanks for pointing this out, but this does not address the problem. I don't see why separation of concerns is an anti pattern. I do not want to pollute namespaces and separating code makes you think how it should work and be structured. Implement a feature in `gsctl` or `api`. Then you maybe feel the pain. Fewer bigger packages are not helping with anything here as I see it right now.

**Comment by kopiczko** [comment]
I don't have much to do with `gsctl` or `api`, but in `apiextensions` we have a flat structure that makes sense. Types are grouped by kubernetes groups. That's a functionality. They are versinoined together. This is the upstream approach.

> I don't see why separation of concerns is an anti pattern.

I didn't say separation of concerns isn't an anti pattern. I think it's a good thing.

`ResponseAWS` doesn't make sense w/o `Response`. `lister.Response` is response of the API in package `lister`. `lister.ResponseAWS` is part of response  of the API in package `lister`. Where is the separation of concerns? They are concerning the same thing. Putting them in separate packages would mean splitting code concerning the same functionality which makes it difficult to understand and leads to bad API design IMO.

> I do not want to pollute namespaces and separating code makes you think how it should work and be structured.

I don't want to pollute whole project with tons of namespaces not encapsulating any functionality. Such separation doesn't involve any thinking. It's just naming package after variable name.

> Fewer bigger packages are not helping with anything here as I see it right now.

It doesn't make sense for me to jump around the folders and files to find out how the type should look like. Consider for example `AWSConfig` from `apiextensions`. Putting it all even in separate directories/files would make it way harder to realize how the root type (AWSConfig) looks like as a whole. You can just read the file from top to bottom to learn about the type as a whole. Jumping around files - maybe fine, I prefer not doing so. Jumping around directories - definitely would slow me down. I would be barely able to grasp how the wole structure looks like. That's why I'm against.

In general I think packages should be used to encapsulate units of functionality. They shouldn't be used as a type structure.

**Comment by xh3b4sd** [comment]
Hold your horses. Misunderstanding. I want to have all response type in their own package together, separated from the service implementation. When having defaulting and validation separated, you MUST have the types in a separate package to mitigate an import cycle. I did not say that you should have different packages for the response related types. They should be in the same package. I would like to see them in different files, but yeah.

**Comment by kopiczko** [comment]
In order to "version" response types?

**Comment by xh3b4sd** [comment]
**to mitigate an import cycle**

**Comment by kopiczko** [comment]
Ack. I still don't fully get why is that but I don't think it's so important in scope of this PR. Going with that.

**Pull request merged**
